jobs:
  build-chain:
    concurrency:
      cancel-in-progress: true
      group: fdb-${{ github.head_ref }}
    if: contains(github.event.pull_request.labels.*.name, 'run_fdb')
    name: ${{ matrix.os }} - Java ${{ matrix.java-version }} - Maven
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: ${{ matrix.os == 'ubuntu-latest' }}
      name: Clean Disk Space
      uses: kiegroup/kie-ci/.ci/actions/ubuntu-disk-space@main
    - continue-on-error: true
      if: ${{ matrix.os == 'windows-latest' }}
      name: Support long paths
      uses: kiegroup/kie-ci/.ci/actions/long-paths@main
    - continue-on-error: true
      name: Java and Maven Setup
      uses: kiegroup/kie-ci/.ci/actions/maven@main
      with:
        cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version
          }}
        java-version: ${{ matrix.java-version }}
        maven-version: ${{ matrix.maven-version }}
    - continue-on-error: true
      name: Build Chain
      uses: kiegroup/kie-ci/.ci/actions/build-chain@main
      with:
        annotations-prefix: ${{ runner.os }}-${{ matrix.java-version }}/${{ matrix.maven-version
          }}
        definition-file: https://raw.githubusercontent.com/${GROUP:kiegroup}/optaplanner/${BRANCH:main}/.ci/buildchain-config.yaml
        flow-type: full-downstream
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      if: ${{ always() }}
      name: Surefire Report
      uses: kiegroup/kie-ci/.ci/actions/surefire-report@main
    strategy:
      fail-fast: false
      matrix:
        java-version:
        - 17
        maven-version:
        - 3.9.3
        os:
        - ubuntu-latest
name: Build Chain FDB
on:
  repository_dispatch:
    types: trigger-ga___full-downstream.yml
