jobs:
  generate-status-page:
    concurrency:
      cancel-in-progress: true
      group: generate-status-page
    if: github.repository == 'kiegroup/optaplanner'
    name: Generate status page
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Generate status page
      uses: kiegroup/chain-status/.ci/actions/generate-app@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        info-md-url: https://raw.githubusercontent.com/kiegroup/optaplanner/main/.ci/chain-status-info.md
    strategy:
      fail-fast: true
      matrix:
        os:
        - ubuntu-latest
name: Generate status page
on:
  repository_dispatch:
    types: trigger-ga___generate_status_page.yaml
