jobs:
  dsl-tests:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.repository.name }}_dsl_tests-${{ github.head_ref }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: DSL tests
      uses: kiegroup/kie-ci/.ci/actions/dsl-tests@main
      with:
        branch-config-file-repo: kiegroup/optaplanner
        main-config-file-path: .ci/jenkins/config/main.yaml
        main-config-file-repo: kiegroup/optaplanner
        project: optaplanner
name: Jenkins Tests
on:
  repository_dispatch:
    types: trigger-ga___jenkins-tests-PR.yml
