defaults:
  run:
    shell: bash
jobs:
  build-chain:
    concurrency:
      cancel-in-progress: true
      group: pull_request-${{ github.event_name }}-${{ github.head_ref }}-${{ matrix.os
        }}-${{ matrix.java-version }}
    name: ${{ matrix.os }} - Java ${{ matrix.java-version }} - Maven
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: ${{ matrix.os == 'ubuntu-latest' }}
      name: Clean Disk Space
      uses: kiegroup/kie-ci/.ci/actions/ubuntu-disk-space@main
    - continue-on-error: true
      if: ${{ matrix.os == 'windows-latest' }}
      name: Support long paths
      uses: kiegroup/kie-ci/.ci/actions/long-paths@main
    - continue-on-error: true
      name: Java and Maven Setup
      uses: kiegroup/kie-ci/.ci/actions/maven@main
      with:
        cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version
          }}
        java-version: ${{ matrix.java-version }}
        maven-version: ${{ matrix.maven-version }}
    - continue-on-error: true
      if: github.event_name == 'pull_request'
      name: Set FLOW_TYPE to pull-request
      run: echo "FLOW_TYPE=pull-request" >> $GITHUB_ENV
    - continue-on-error: true
      if: github.event_name == 'push'
      name: Set FLOW_TYPE to branch
      run: echo "FLOW_TYPE=branch" >> $GITHUB_ENV
    - continue-on-error: true
      env:
        MAVEN_OPTS: -Xmx2048m
      name: Build Chain
      uses: kiegroup/kie-ci/.ci/actions/build-chain@main
      with:
        annotations-prefix: ${{ runner.os }}-${{ matrix.java-version }}/${{ matrix.maven-version
          }}
        definition-file: https://raw.githubusercontent.com/${GROUP:kiegroup}/optaplanner/${BRANCH:main}/.ci/buildchain-config.yaml
        flow-type: ${{ env.FLOW_TYPE }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        starting-project: kiegroup/optaplanner
    - continue-on-error: true
      if: ${{ always() }}
      name: Surefire Report
      uses: kiegroup/kie-ci/.ci/actions/surefire-report@main
      with:
        report_paths: '**/*-reports/TEST-*.xml'
    strategy:
      fail-fast: false
      matrix:
        java-version:
        - 11
        - 17
        - 20
        maven-version:
        - 3.9.3
        os:
        - ubuntu-latest
        - windows-latest
    timeout-minutes: 120
name: Build Chain
on:
  repository_dispatch:
    types: trigger-ga___pull_request.yml
