env:
  ECOSYSTEM_CI_REPO: quarkusio/quarkus-ecosystem-ci
  ECOSYSTEM_CI_REPO_FILE: context.yaml
  ECOSYSTEM_CI_REPO_PATH: optaplanner
jobs:
  build:
    if: github.actor == 'quarkusbot'
    name: ${{ matrix.os }} - Java ${{ matrix.java-version }} - Maven
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Install yq
      run: sudo add-apt-repository ppa:rmescandon/yq && sudo apt update && sudo apt
        install yq -y
    - continue-on-error: true
      name: Java and Maven Setup
      uses: kiegroup/kie-ci/.ci/actions/maven@main
      with:
        cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version
          }}
        java-version: ${{ matrix.java-version }}
        maven-version: ${{ matrix.maven-version }}
    - continue-on-error: true
      name: Checkout repo
      uses: actions/checkout@v4
      with:
        path: current-repo
        ref: main
    - continue-on-error: true
      name: Checkout Ecosystem
      uses: actions/checkout@v4
      with:
        path: ecosystem-ci
        ref: main
        repository: ${{ env.ECOSYSTEM_CI_REPO }}
    - continue-on-error: true
      env:
        ECOSYSTEM_CI_TOKEN: ${{ secrets.ECOSYSTEM_CI_TOKEN }}
      name: Setup and Run Tests
      run: ./ecosystem-ci/setup-and-test
    strategy:
      fail-fast: false
      matrix:
        java-version:
        - 17
        maven-version:
        - 3.9.3
        os:
        - ubuntu-latest
name: Quarkus ecosystem
on:
  repository_dispatch:
    types: trigger-ga___quarkus-snapshot.yml
